### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by ghost** [omni-viral/xfg-rs#13]
There have been no update for a while and some referenced package (gfx_render) is explicitly stated to be discontinued. What is the state of this project ? Is there some successor ?

**Comment by zakarumych** [comment]
Yes. This project was continued as more self contained project https://github.com/omni-viral/rendy
In essence rendy is xfg + gfx-renderer + gfx-memory and more.
I guess I should put that into readme.

**Comment by ghost** [comment]
Thanks, great. I see a lot of work goes into rendy.

**Comment by zakarumych** [comment]
@zpgaal yeah, we work together with other guys from amethyst team to push rendy toward release and helped gfx team to release gfx-hal.

**Comment by ghost** [comment]
As readme's been updated I think it can be closed
